import type { TSchema } from "@sinclair/typebox";
import {
  AgentEventSchema,
  AgentIdentityParamsSchema,
  AgentIdentityResultSchema,
  AgentParamsSchema,
  AgentWaitParamsSchema,
  PollParamsSchema,
  SendParamsSchema,
  WakeParamsSchema,
} from "./agent.js";
import {
  AgentSummarySchema,
  AgentsCreateParamsSchema,
  AgentsCreateResultSchema,
  AgentsDeleteParamsSchema,
  AgentsDeleteResultSchema,
  AgentsFileEntrySchema,
  AgentsFilesGetParamsSchema,
  AgentsFilesGetResultSchema,
  AgentsFilesListParamsSchema,
  AgentsFilesListResultSchema,
  AgentsFilesSetParamsSchema,
  AgentsFilesSetResultSchema,
  AgentsWorkspaceFileDocumentSchema,
  AgentsWorkspaceFileEntrySchema,
  AgentsWorkspaceFilesDeleteParamsSchema,
  AgentsWorkspaceFilesDeleteResultSchema,
  AgentsWorkspaceFilesGetParamsSchema,
  AgentsWorkspaceFilesGetResultSchema,
  AgentsWorkspaceFilesListParamsSchema,
  AgentsWorkspaceFilesListResultSchema,
  AgentsWorkspaceFilesMkdirParamsSchema,
  AgentsWorkspaceFilesMkdirResultSchema,
  AgentsWorkspaceFilesMoveParamsSchema,
  AgentsWorkspaceFilesMoveResultSchema,
  AgentsWorkspaceFilesSetParamsSchema,
  AgentsWorkspaceFilesSetResultSchema,
  AgentsListParamsSchema,
  AgentsListResultSchema,
  AgentsUpdateParamsSchema,
  AgentsUpdateResultSchema,
  ModelChoiceSchema,
  ModelsListParamsSchema,
  ModelsListResultSchema,
  ResolvedCapabilityClassSchema,
  ResolvedCapabilityDenyReasonSchema,
  ResolvedCapabilityEvidenceSchema,
  ResolvedCapabilityKindSchema,
  ResolvedCapabilityManifestSchema,
  ResolvedCapabilityPolicySchema,
  ResolvedCapabilityPolicySourceSchema,
  ResolvedCapabilityProjectionEvidenceSchema,
  ResolvedCapabilityProviderEvidenceSchema,
  ResolvedCapabilityRemoteEvidenceSchema,
  ResolvedCapabilityRuntimeContextSchema,
  ResolvedCapabilityRuntimeEvidenceSchema,
  ResolvedCapabilityUnavailableReasonSchema,
  ResolvedSkillBlockedCapabilitySchema,
  ResolvedSkillCapabilitySchema,
  ResolvedSkillLocalCapabilitySchema,
  ResolvedSkillRemoteCapabilitySchema,
  ResolvedSkillUnsupportedCapabilitySchema,
  ResolvedToolBlockedCapabilitySchema,
  ResolvedToolBrokeredCapabilitySchema,
  ResolvedToolCapabilitySchema,
  ResolvedToolLocalCapabilitySchema,
  ResolvedToolRemoteCapabilitySchema,
  ResolvedToolUnsupportedCapabilitySchema,
  SkillsBinsParamsSchema,
  SkillsBinsResultSchema,
  SkillsInstallParamsSchema,
  SkillsStatusResultSchema,
  SkillsStatusParamsSchema,
  SkillsUpdateParamsSchema,
  SkillInstallOptionSchema,
  SkillRemoteSatisfiedSchema,
  SkillStatusConfigCheckSchema,
  SkillStatusEntrySchema,
  SkillStatusRequirementsSchema,
  ToolCatalogEntrySchema,
  ToolCatalogGroupSchema,
  ToolCatalogProfileSchema,
  ToolsCatalogParamsSchema,
  ToolsCatalogResultSchema,
} from "./agents-models-skills.js";
import {
  ChannelsLogoutParamsSchema,
  TalkConfigParamsSchema,
  TalkConfigResultSchema,
  ChannelsStatusParamsSchema,
  ChannelsStatusResultSchema,
  TalkModeParamsSchema,
  WebLoginStartParamsSchema,
  WebLoginWaitParamsSchema,
} from "./channels.js";
import {
  ConfigApplyParamsSchema,
  DoctorRunParamsSchema,
  ConfigGetParamsSchema,
  ConfigPatchParamsSchema,
  ConfigSchemaParamsSchema,
  ConfigSchemaResponseSchema,
  ConfigSetParamsSchema,
  UpdateRunParamsSchema,
} from "./config.js";
import {
  CronAddParamsSchema,
  CronJobSchema,
  CronListParamsSchema,
  CronRemoveParamsSchema,
  CronRunLogEntrySchema,
  CronRunParamsSchema,
  CronRunsParamsSchema,
  CronStatusParamsSchema,
  CronUpdateParamsSchema,
} from "./cron.js";
import {
  DevicePairApproveParamsSchema,
  DevicePairListParamsSchema,
  DevicePairRemoveParamsSchema,
  DevicePairRejectParamsSchema,
  DevicePairRequestedEventSchema,
  DevicePairResolvedEventSchema,
  DeviceTokenRevokeParamsSchema,
  DeviceTokenRotateParamsSchema,
} from "./devices.js";
import {
  ExecApprovalsGetParamsSchema,
  ExecApprovalsNodeGetParamsSchema,
  ExecApprovalsNodeSetParamsSchema,
  ExecApprovalsSetParamsSchema,
  ExecApprovalsSnapshotSchema,
  ExecApprovalRequestParamsSchema,
  ExecApprovalResolveParamsSchema,
} from "./exec-approvals.js";
import {
  ConnectParamsSchema,
  ErrorShapeSchema,
  EventFrameSchema,
  GatewayFrameSchema,
  HelloOkSchema,
  RequestFrameSchema,
  ResponseFrameSchema,
  ShutdownEventSchema,
  TickEventSchema,
} from "./frames.js";
import {
  KanbanActivitySchema,
  KanbanActorSchema,
  KanbanBoardGetParamsSchema,
  KanbanBoardSchema,
  KanbanBoardSnapshotSchema,
  KanbanCardDetailSchema,
  KanbanCardSchema,
  KanbanCardsCreateParamsSchema,
  KanbanCardsGetParamsSchema,
  KanbanCardsListParamsSchema,
  KanbanCardsListResultSchema,
  KanbanCardsMoveParamsSchema,
  KanbanCardsUpdateParamsSchema,
  KanbanChecklistsAddItemParamsSchema,
  KanbanChecklistsAddItemResultSchema,
  KanbanChecklistsDeleteItemParamsSchema,
  KanbanChecklistsDeleteItemResultSchema,
  KanbanChecklistsUpdateItemParamsSchema,
  KanbanChecklistsUpdateItemResultSchema,
  KanbanChecklistItemSchema,
  KanbanCommentSchema,
  KanbanCommentsAddParamsSchema,
  KanbanCommentsAddResultSchema,
  KanbanCommentsListParamsSchema,
  KanbanCommentsListResultSchema,
  KanbanLaneSchema,
  KanbanNotificationSchema,
  KanbanScopedCredentialMetadataSchema,
} from "./kanban.js";
import {
  ChatAbortParamsSchema,
  ChatEventSchema,
  ChatHistoryParamsSchema,
  ChatInjectParamsSchema,
  ChatSendParamsSchema,
  LogsTailParamsSchema,
  LogsTailResultSchema,
} from "./logs-chat.js";
import {
  NodeDescribeParamsSchema,
  NodeEventParamsSchema,
  NodeInvokeParamsSchema,
  NodeInvokeResultParamsSchema,
  NodeInvokeRequestEventSchema,
  NodeListParamsSchema,
  NodePairApproveParamsSchema,
  NodePairListParamsSchema,
  NodePairRejectParamsSchema,
  NodePairRequestParamsSchema,
  NodePairVerifyParamsSchema,
  NodeRenameParamsSchema,
} from "./nodes.js";
import { PushTestParamsSchema, PushTestResultSchema } from "./push.js";
import {
  SecretsReloadParamsSchema,
  SecretsResolveAssignmentSchema,
  SecretsResolveParamsSchema,
  SecretsResolveResultSchema,
} from "./secrets.js";
import {
  SessionsCompactParamsSchema,
  SessionsDeleteParamsSchema,
  SessionsListParamsSchema,
  SessionsPatchParamsSchema,
  SessionsPreviewParamsSchema,
  SessionsResetParamsSchema,
  SessionsResolveParamsSchema,
  SessionsUsageParamsSchema,
} from "./sessions.js";
import { PresenceEntrySchema, SnapshotSchema, StateVersionSchema } from "./snapshot.js";
import {
  WizardCancelParamsSchema,
  WizardNextParamsSchema,
  WizardNextResultSchema,
  WizardStartParamsSchema,
  WizardStartResultSchema,
  WizardStatusParamsSchema,
  WizardStatusResultSchema,
  WizardStepSchema,
} from "./wizard.js";

export const ProtocolSchemas = {
  ConnectParams: ConnectParamsSchema,
  HelloOk: HelloOkSchema,
  RequestFrame: RequestFrameSchema,
  ResponseFrame: ResponseFrameSchema,
  EventFrame: EventFrameSchema,
  GatewayFrame: GatewayFrameSchema,
  PresenceEntry: PresenceEntrySchema,
  StateVersion: StateVersionSchema,
  Snapshot: SnapshotSchema,
  ErrorShape: ErrorShapeSchema,
  AgentEvent: AgentEventSchema,
  SendParams: SendParamsSchema,
  PollParams: PollParamsSchema,
  AgentParams: AgentParamsSchema,
  AgentIdentityParams: AgentIdentityParamsSchema,
  AgentIdentityResult: AgentIdentityResultSchema,
  AgentWaitParams: AgentWaitParamsSchema,
  WakeParams: WakeParamsSchema,
  NodePairRequestParams: NodePairRequestParamsSchema,
  NodePairListParams: NodePairListParamsSchema,
  NodePairApproveParams: NodePairApproveParamsSchema,
  NodePairRejectParams: NodePairRejectParamsSchema,
  NodePairVerifyParams: NodePairVerifyParamsSchema,
  NodeRenameParams: NodeRenameParamsSchema,
  NodeListParams: NodeListParamsSchema,
  NodeDescribeParams: NodeDescribeParamsSchema,
  NodeInvokeParams: NodeInvokeParamsSchema,
  NodeInvokeResultParams: NodeInvokeResultParamsSchema,
  NodeEventParams: NodeEventParamsSchema,
  NodeInvokeRequestEvent: NodeInvokeRequestEventSchema,
  PushTestParams: PushTestParamsSchema,
  PushTestResult: PushTestResultSchema,
  SecretsReloadParams: SecretsReloadParamsSchema,
  SecretsResolveParams: SecretsResolveParamsSchema,
  SecretsResolveAssignment: SecretsResolveAssignmentSchema,
  SecretsResolveResult: SecretsResolveResultSchema,
  SessionsListParams: SessionsListParamsSchema,
  SessionsPreviewParams: SessionsPreviewParamsSchema,
  SessionsResolveParams: SessionsResolveParamsSchema,
  SessionsPatchParams: SessionsPatchParamsSchema,
  SessionsResetParams: SessionsResetParamsSchema,
  SessionsDeleteParams: SessionsDeleteParamsSchema,
  SessionsCompactParams: SessionsCompactParamsSchema,
  SessionsUsageParams: SessionsUsageParamsSchema,
  KanbanActor: KanbanActorSchema,
  KanbanBoard: KanbanBoardSchema,
  KanbanLane: KanbanLaneSchema,
  KanbanCard: KanbanCardSchema,
  KanbanChecklistItem: KanbanChecklistItemSchema,
  KanbanComment: KanbanCommentSchema,
  KanbanActivity: KanbanActivitySchema,
  KanbanNotification: KanbanNotificationSchema,
  KanbanScopedCredentialMetadata: KanbanScopedCredentialMetadataSchema,
  KanbanBoardSnapshot: KanbanBoardSnapshotSchema,
  KanbanCardDetail: KanbanCardDetailSchema,
  KanbanBoardGetParams: KanbanBoardGetParamsSchema,
  KanbanCardsListParams: KanbanCardsListParamsSchema,
  KanbanCardsListResult: KanbanCardsListResultSchema,
  KanbanCardsGetParams: KanbanCardsGetParamsSchema,
  KanbanCardsCreateParams: KanbanCardsCreateParamsSchema,
  KanbanCardsUpdateParams: KanbanCardsUpdateParamsSchema,
  KanbanCardsMoveParams: KanbanCardsMoveParamsSchema,
  KanbanChecklistsAddItemParams: KanbanChecklistsAddItemParamsSchema,
  KanbanChecklistsAddItemResult: KanbanChecklistsAddItemResultSchema,
  KanbanChecklistsUpdateItemParams: KanbanChecklistsUpdateItemParamsSchema,
  KanbanChecklistsUpdateItemResult: KanbanChecklistsUpdateItemResultSchema,
  KanbanChecklistsDeleteItemParams: KanbanChecklistsDeleteItemParamsSchema,
  KanbanChecklistsDeleteItemResult: KanbanChecklistsDeleteItemResultSchema,
  KanbanCommentsListParams: KanbanCommentsListParamsSchema,
  KanbanCommentsListResult: KanbanCommentsListResultSchema,
  KanbanCommentsAddParams: KanbanCommentsAddParamsSchema,
  KanbanCommentsAddResult: KanbanCommentsAddResultSchema,
  ConfigGetParams: ConfigGetParamsSchema,
  ConfigSetParams: ConfigSetParamsSchema,
  ConfigApplyParams: ConfigApplyParamsSchema,
  ConfigPatchParams: ConfigPatchParamsSchema,
  DoctorRunParams: DoctorRunParamsSchema,
  ConfigSchemaParams: ConfigSchemaParamsSchema,
  ConfigSchemaResponse: ConfigSchemaResponseSchema,
  WizardStartParams: WizardStartParamsSchema,
  WizardNextParams: WizardNextParamsSchema,
  WizardCancelParams: WizardCancelParamsSchema,
  WizardStatusParams: WizardStatusParamsSchema,
  WizardStep: WizardStepSchema,
  WizardNextResult: WizardNextResultSchema,
  WizardStartResult: WizardStartResultSchema,
  WizardStatusResult: WizardStatusResultSchema,
  TalkModeParams: TalkModeParamsSchema,
  TalkConfigParams: TalkConfigParamsSchema,
  TalkConfigResult: TalkConfigResultSchema,
  ChannelsStatusParams: ChannelsStatusParamsSchema,
  ChannelsStatusResult: ChannelsStatusResultSchema,
  ChannelsLogoutParams: ChannelsLogoutParamsSchema,
  WebLoginStartParams: WebLoginStartParamsSchema,
  WebLoginWaitParams: WebLoginWaitParamsSchema,
  AgentSummary: AgentSummarySchema,
  AgentsCreateParams: AgentsCreateParamsSchema,
  AgentsCreateResult: AgentsCreateResultSchema,
  AgentsUpdateParams: AgentsUpdateParamsSchema,
  AgentsUpdateResult: AgentsUpdateResultSchema,
  AgentsDeleteParams: AgentsDeleteParamsSchema,
  AgentsDeleteResult: AgentsDeleteResultSchema,
  AgentsFileEntry: AgentsFileEntrySchema,
  AgentsFilesListParams: AgentsFilesListParamsSchema,
  AgentsFilesListResult: AgentsFilesListResultSchema,
  AgentsFilesGetParams: AgentsFilesGetParamsSchema,
  AgentsFilesGetResult: AgentsFilesGetResultSchema,
  AgentsFilesSetParams: AgentsFilesSetParamsSchema,
  AgentsFilesSetResult: AgentsFilesSetResultSchema,
  AgentsWorkspaceFileEntry: AgentsWorkspaceFileEntrySchema,
  AgentsWorkspaceFileDocument: AgentsWorkspaceFileDocumentSchema,
  AgentsWorkspaceFilesListParams: AgentsWorkspaceFilesListParamsSchema,
  AgentsWorkspaceFilesListResult: AgentsWorkspaceFilesListResultSchema,
  AgentsWorkspaceFilesGetParams: AgentsWorkspaceFilesGetParamsSchema,
  AgentsWorkspaceFilesGetResult: AgentsWorkspaceFilesGetResultSchema,
  AgentsWorkspaceFilesSetParams: AgentsWorkspaceFilesSetParamsSchema,
  AgentsWorkspaceFilesSetResult: AgentsWorkspaceFilesSetResultSchema,
  AgentsWorkspaceFilesDeleteParams: AgentsWorkspaceFilesDeleteParamsSchema,
  AgentsWorkspaceFilesDeleteResult: AgentsWorkspaceFilesDeleteResultSchema,
  AgentsWorkspaceFilesMkdirParams: AgentsWorkspaceFilesMkdirParamsSchema,
  AgentsWorkspaceFilesMkdirResult: AgentsWorkspaceFilesMkdirResultSchema,
  AgentsWorkspaceFilesMoveParams: AgentsWorkspaceFilesMoveParamsSchema,
  AgentsWorkspaceFilesMoveResult: AgentsWorkspaceFilesMoveResultSchema,
  AgentsListParams: AgentsListParamsSchema,
  AgentsListResult: AgentsListResultSchema,
  ModelChoice: ModelChoiceSchema,
  ModelsListParams: ModelsListParamsSchema,
  ModelsListResult: ModelsListResultSchema,
  ResolvedCapabilityClass: ResolvedCapabilityClassSchema,
  ResolvedCapabilityKind: ResolvedCapabilityKindSchema,
  ResolvedCapabilityDenyReason: ResolvedCapabilityDenyReasonSchema,
  ResolvedCapabilityUnavailableReason: ResolvedCapabilityUnavailableReasonSchema,
  ResolvedCapabilityRuntimeContext: ResolvedCapabilityRuntimeContextSchema,
  ResolvedCapabilityPolicySource: ResolvedCapabilityPolicySourceSchema,
  ResolvedCapabilityPolicy: ResolvedCapabilityPolicySchema,
  ResolvedCapabilityRuntimeEvidence: ResolvedCapabilityRuntimeEvidenceSchema,
  ResolvedCapabilityProjectionEvidence: ResolvedCapabilityProjectionEvidenceSchema,
  ResolvedCapabilityProviderEvidence: ResolvedCapabilityProviderEvidenceSchema,
  ResolvedCapabilityRemoteEvidence: ResolvedCapabilityRemoteEvidenceSchema,
  ResolvedCapabilityEvidence: ResolvedCapabilityEvidenceSchema,
  SkillStatusRequirements: SkillStatusRequirementsSchema,
  SkillStatusConfigCheck: SkillStatusConfigCheckSchema,
  SkillInstallOption: SkillInstallOptionSchema,
  SkillRemoteSatisfied: SkillRemoteSatisfiedSchema,
  ResolvedSkillLocalCapability: ResolvedSkillLocalCapabilitySchema,
  ResolvedSkillRemoteCapability: ResolvedSkillRemoteCapabilitySchema,
  ResolvedSkillBlockedCapability: ResolvedSkillBlockedCapabilitySchema,
  ResolvedSkillUnsupportedCapability: ResolvedSkillUnsupportedCapabilitySchema,
  ResolvedSkillCapability: ResolvedSkillCapabilitySchema,
  ResolvedToolLocalCapability: ResolvedToolLocalCapabilitySchema,
  ResolvedToolBrokeredCapability: ResolvedToolBrokeredCapabilitySchema,
  ResolvedToolRemoteCapability: ResolvedToolRemoteCapabilitySchema,
  ResolvedToolBlockedCapability: ResolvedToolBlockedCapabilitySchema,
  ResolvedToolUnsupportedCapability: ResolvedToolUnsupportedCapabilitySchema,
  ResolvedToolCapability: ResolvedToolCapabilitySchema,
  ResolvedCapabilityManifest: ResolvedCapabilityManifestSchema,
  SkillStatusEntry: SkillStatusEntrySchema,
  SkillsStatusParams: SkillsStatusParamsSchema,
  SkillsStatusResult: SkillsStatusResultSchema,
  ToolsCatalogParams: ToolsCatalogParamsSchema,
  ToolCatalogProfile: ToolCatalogProfileSchema,
  ToolCatalogEntry: ToolCatalogEntrySchema,
  ToolCatalogGroup: ToolCatalogGroupSchema,
  ToolsCatalogResult: ToolsCatalogResultSchema,
  SkillsBinsParams: SkillsBinsParamsSchema,
  SkillsBinsResult: SkillsBinsResultSchema,
  SkillsInstallParams: SkillsInstallParamsSchema,
  SkillsUpdateParams: SkillsUpdateParamsSchema,
  CronJob: CronJobSchema,
  CronListParams: CronListParamsSchema,
  CronStatusParams: CronStatusParamsSchema,
  CronAddParams: CronAddParamsSchema,
  CronUpdateParams: CronUpdateParamsSchema,
  CronRemoveParams: CronRemoveParamsSchema,
  CronRunParams: CronRunParamsSchema,
  CronRunsParams: CronRunsParamsSchema,
  CronRunLogEntry: CronRunLogEntrySchema,
  LogsTailParams: LogsTailParamsSchema,
  LogsTailResult: LogsTailResultSchema,
  ExecApprovalsGetParams: ExecApprovalsGetParamsSchema,
  ExecApprovalsSetParams: ExecApprovalsSetParamsSchema,
  ExecApprovalsNodeGetParams: ExecApprovalsNodeGetParamsSchema,
  ExecApprovalsNodeSetParams: ExecApprovalsNodeSetParamsSchema,
  ExecApprovalsSnapshot: ExecApprovalsSnapshotSchema,
  ExecApprovalRequestParams: ExecApprovalRequestParamsSchema,
  ExecApprovalResolveParams: ExecApprovalResolveParamsSchema,
  DevicePairListParams: DevicePairListParamsSchema,
  DevicePairApproveParams: DevicePairApproveParamsSchema,
  DevicePairRejectParams: DevicePairRejectParamsSchema,
  DevicePairRemoveParams: DevicePairRemoveParamsSchema,
  DeviceTokenRotateParams: DeviceTokenRotateParamsSchema,
  DeviceTokenRevokeParams: DeviceTokenRevokeParamsSchema,
  DevicePairRequestedEvent: DevicePairRequestedEventSchema,
  DevicePairResolvedEvent: DevicePairResolvedEventSchema,
  ChatHistoryParams: ChatHistoryParamsSchema,
  ChatSendParams: ChatSendParamsSchema,
  ChatAbortParams: ChatAbortParamsSchema,
  ChatInjectParams: ChatInjectParamsSchema,
  ChatEvent: ChatEventSchema,
  UpdateRunParams: UpdateRunParamsSchema,
  TickEvent: TickEventSchema,
  ShutdownEvent: ShutdownEventSchema,
} satisfies Record<string, TSchema>;

export const PROTOCOL_VERSION = 3 as const;
