services:
  moltbot-gateway:
    image: ${CLAWDBOT_IMAGE:-moltbot:local}
    environment:
      HOME: /home/node
      TERM: xterm-256color
      CLAWDBOT_GATEWAY_TOKEN: ${CLAWDBOT_GATEWAY_TOKEN}
      CLAUDE_AI_SESSION_KEY: ${CLAUDE_AI_SESSION_KEY}
      CLAUDE_WEB_SESSION_KEY: ${CLAUDE_WEB_SESSION_KEY}
      CLAUDE_WEB_COOKIE: ${CLAUDE_WEB_COOKIE}
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      CLAWDBOT_STATE_DIR: /home/node/.clawdbot
      CLAWDBOT_GATEWAY_PORT: ${CLAWDBOT_GATEWAY_PORT}
      CLAWDBOT_BRIDGE_PORT: ${CLAWDBOT_BRIDGE_PORT}
    volumes:
      - ${CLAWDBOT_CONFIG_DIR}:/home/node/.clawdbot
      - ${CLAWDBOT_WORKSPACE_DIR}:/home/node/clawd
    ports:
      - "${CLAWDBOT_GATEWAY_PORT}:${CLAWDBOT_GATEWAY_PORT}"
      - "${CLAWDBOT_BRIDGE_PORT}:${CLAWDBOT_BRIDGE_PORT}"
    init: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "dist/index.js", "health", "--json", "--timeout", "10000"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 30s
    command:
      [
        "node",
        "dist/index.js",
        "gateway",
        "--bind",
        "${CLAWDBOT_GATEWAY_BIND:-loopback}",
        "--port",
<<<<<<< HEAD
<<<<<<< HEAD
        "${CLAWDBOT_GATEWAY_PORT}",
        "--allow-unconfigured"
=======
        "18789"
>>>>>>> bc5b0c82a (fix(docker): avoid using host port in gateway command (#5110) (thanks @mise42))
=======
        "18789",
>>>>>>> 443ee26af (chore: oxfmt fixes)
      ]

  moltbot-cli:
    image: ${CLAWDBOT_IMAGE:-moltbot:local}
    environment:
      HOME: /home/node
      TERM: xterm-256color
      BROWSER: echo
      CLAUDE_AI_SESSION_KEY: ${CLAUDE_AI_SESSION_KEY}
      CLAUDE_WEB_SESSION_KEY: ${CLAUDE_WEB_SESSION_KEY}
      CLAUDE_WEB_COOKIE: ${CLAUDE_WEB_COOKIE}
    volumes:
      - ${CLAWDBOT_CONFIG_DIR}:/home/node/.clawdbot
      - ${CLAWDBOT_WORKSPACE_DIR}:/home/node/clawd
    stdin_open: true
    tty: true
    init: true
    entrypoint: ["node", "dist/index.js"]
