packages:
  - .
  - ui
  - packages/*
  - extensions/*

onlyBuiltDependencies:
  - '@whiskeysockets/baileys'
  - '@lydell/node-pty'
  - '@matrix-org/matrix-sdk-crypto-nodejs'
  - authenticate-pam
  - esbuild
  - node-llama-cpp
  - protobufjs
  - sharp
  - '@napi-rs/canvas'
